apiVersion: v1
kind: Service
metadata:
  name: dh-local
  labels:
    run: dh-local
spec:
  type: NodePort
  ports:
    - port: 10000
      targetPort: 10000
      protocol: TCP
      nodePort: 30080
      name: http
#    - port: 9001
#      targetPort: 9090
#      protocol: TCP
#      nodePort: 30090
#      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30443
      name: https
  selector:
    run: dh-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dh-local
spec:
  selector:
    matchLabels:
      run: dh-local
  replicas: 1
  template:
    metadata:
      labels:
        run: dh-local
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: nginxsecret
        - name: configmap-volume
          configMap:
            name: nginxconfigmap
        - name: cred-cache
          emptyDir:
            medium: Memory

      containers:

        #
        # grpc-api container.  Where all the stateful brains live
        #
        - name: grpc-api
          image: deephaven/grpc-api:local-build
          imagePullPolicy: Never
          securityContext:
            privileged: false
          # Change tty to true if you want to be able to shell into the box
          tty: true
          env:
          - name: CONTAINER_NAME
            value: grpc-api
          - name: kubernetes.max.concurrent.requests
            value: '1024'
          - name: kubernetes.max.concurrent.requests.per.host
            value: '128'
          - name: JAVA_OPTS
            value: '-Xmx2560m -server -XX:+CMSClassUnloadingEnabled'
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          volumeMounts:
          - name: cred-cache
            mountPath: /root/.ssh
          readinessProbe:
            exec:
              command: [ "/health/grpc_health_probe", "-addr=:8080" ]
            initialDelaySeconds: 2
            periodSeconds: 1
            failureThreshold: 28
          livenessProbe:
            exec:
              command: [ "/health/grpc_health_probe", "-addr=:8080" ]
            initialDelaySeconds: 10
            periodSeconds: 8

        #
        # grpc-proxy: turns http1 grpc web requests into http2 fit for grpc-api to consume
        #
        - name: grpc-proxy
          image: deephaven/grpc-proxy:local-build
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          # Change tty to true if you want to be able to shell into the box
          tty: false
      #    resources:
      #      # See: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md
      #      limits:
      #        # 4 cpus
      #        cpu: '4000m'
      #        # ~8G RAM
      #        memory: '8000Mi'
          env:
          - name: BACKEND_ADDR
            value: "grpc-api:8080"
          - name: CONTAINER_NAME
            value: grpc-proxy
          - name: kubernetes.max.concurrent.requests
            value: '1024'
          - name: kubernetes.max.concurrent.requests.per.host
            value: '128'
          - name: JAVA_OPTS
            value: '-Xmx2560m -server -XX:+CMSClassUnloadingEnabled'
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          volumeMounts:
          - name: cred-cache
            mountPath: /root/.ssh


        #
        # web: serves the web ide and all static resources
        #
        - name: web
          image: deephaven/web:local-build
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          # Change tty to true if you want to be able to shell into the box
          tty: false
          env:
          - name: CONTAINER_NAME
            value: web
          - name: kubernetes.max.concurrent.requests
            value: '1024'
          - name: kubernetes.max.concurrent.requests.per.host
            value: '128'
          - name: JAVA_OPTS
            value: '-Xmx2560m -server -XX:+CMSClassUnloadingEnabled'
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          volumeMounts:
          - name: cred-cache
            mountPath: /root/.ssh


        #
        # envoy: this should really be a stateful set / deployment instead of a container-within-this-pod.
        # As a stateful set, the container would be added automatically to all nodes, plus it would have stable addressing.
        #
        - name: envoy
          image: deephaven/envoy:local-build
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          # Change tty to true if you want to be able to shell into the box
          tty: false
          ports:
            - name: https
              containerPort: 8443
            - name: http
              containerPort: 8181
              protocol: TCP
#          readinessProbe:
#            httpGet:
#              port: https
#              httpHeaders:
#                - name: x-envoy-livenessprobe
#                  value: healthz
#              path: /healthz
#              scheme: HTTPS
          env:
          - name: CONTAINER_NAME
            value: envoy
          - name: kubernetes.max.concurrent.requests
            value: '1024'
          - name: kubernetes.max.concurrent.requests.per.host
            value: '128'
          - name: JAVA_OPTS
            value: '-Xmx2560m -server -XX:+CMSClassUnloadingEnabled'
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          volumeMounts:
          - name: cred-cache
            mountPath: /root/.ssh
