apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dh.svcNameControl }}
  labels:
    {{- include "dhdemo.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/app-protocols: '{"control":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"ports": {
    "control":"dh-backend-envoy"
    }}'
spec:
  type: {{ .Values.service.type }}
  ports:
    -
      name: control
      port: {{ .Values.dh.portControl }}
      targetPort: {{ .Values.dh.portControlInternal }}
      protocol: TCP

  selector:
    dh-purpose: controller
