apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: dh-backend-controller
spec:
  timeoutSec: {{ .Values.dh.backendResponseSeconds }}
  #sessionAffinity:
  #  affinityType: "GENERATED_COOKIE"
  #  affinityCookieTtlSec: {{ .Values.dh.cookieTtlSeconds }}
  healthCheck:
    #requestPath: /grpc.health.v1.Health/Check
    #port: {{ .Values.dh.portGrpcApiInternal }}
    requestPath: /health
    port: {{ .Values.dh.portControl }}
    #type: HTTP2
    type: HTTP
    #requestPath: /ide/
    #port: 8080
    #type: HTTP
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 10