apiVersion: v1
kind: Service
metadata:
  name: {{ include "dhdemo.fullname" . }}
  labels:
    {{- include "dhdemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    -
      name: envoy-client
      port: 10000
      targetPort: 10000
      protocol: TCP
      nodePort: 30080
    -
      name: envoy-admin
      port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30443

  selector:
    {{- include "dhdemo.selectorLabels" . | nindent 4 }}
