apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dh.svcNameGrpc }}
  labels:
    {{- include "dhdemo.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/app-protocols: '{"grpc-api":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"{{ .Values.dh.portGrpcApiInternal }}":{}}}'
    beta.cloud.google.com/backend-config: '{"ports": {
    "grpc-api":"dh-backend-grpc"
    }}'
spec:
  # type: {{ .Values.dh.envoyServiceType }}
  type: NodePort
  ports:
    -
      name: grpc-api
      port: {{ .Values.dh.portGrpcApiInternal }}
      targetPort: {{ .Values.dh.portGrpcApi }}
      protocol: TCP
    #-
    #  name: web-int
    #  port: {{ .Values.dh.portWebInternal }}
    #  targetPort: {{ .Values.dh.portWeb }}
    #  protocol: TCP
  selector:
    {{- include "dhdemo.selectorLabels" . | nindent 4 }}
