apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.dh.ingressName }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.dh.ipAddrName }}
    networking.gke.io/managed-certificates: {{ .Values.dh.certName  }}
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.dh.frontendConfigName }}
spec:
  #tls:
  #- hosts:
  #    - {{ .Values.dh.dnsName }}
  #  secretName: testsecret-tls
  defaultBackend:
    service:
      name: {{ .Values.dh.svcNameGrpc }}
      port:
        number: {{ .Values.dh.portGrpcApiInternal }}
  rules:
    - http:
        paths:
          - path: /ide/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dh.svcNameWeb }}
                port:
                  number: {{ .Values.dh.portWebInternal }}
          - path: /jsapi/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dh.svcNameWeb }}
                port:
                  number: {{ .Values.dh.portWebInternal }}
          - path: /notebooks/*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dh.svcNameWeb }}
                port:
                  number: {{ .Values.dh.portWebInternal }}
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ .Values.dh.svcNameWeb }}
                port:
                  number: {{ .Values.dh.portWebInternal }}
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dh.svcNameGrpc }}
                port:
                  number: {{ .Values.dh.portGrpcApiInternal }}
